### ISSUE TITLE
Getting some errors

### ISSUE THREAD

**Issue by mmjaeger** [marktimemedia/page-components-for-wordpress-themes#1]
Fatal error: Uncaught Error: Call to undefined function get_field() in /Users/Marco/Sites/cms/wp-mmjaeger/wp-content/plugins/acf-page-components/lib/mtm-config.php:92 Stack trace: #0 /Users/Marco/Sites/cms/wp-mmjaeger/wp-content/plugins/acf-page-components/mtm-page-components.php(26): require_once() #1 /Users/Marco/Sites/cms/wp-mmjaeger/wp-settings.php(342): include_once('/Users/Marco/Si...') #2 /Users/Marco/Sites/cms/wp-mmjaeger/wp-config.php(112): require_once('/Users/Marco/Si...') #3 /Users/Marco/Sites/cms/wp-mmjaeger/wp-load.php(37): require_once('/Users/Marco/Si...') #4 /Users/Marco/Sites/cms/wp-mmjaeger/wp-admin/admin.php(34): require_once('/Users/Marco/Si...') #5 /Users/Marco/Sites/cms/wp-mmjaeger/wp-admin/plugins.php(10): require_once('/Users/Marco/Si...') #6 {main} thrown in /Users/Marco/Sites/cms/wp-mmjaeger/wp-content/plugins/acf-page-components/lib/mtm-config.php on line 92

**Comment by marktimemedia** [comment]
Are you using this along with Advanced Custom Fields Pro? That is where that function is defined. This is just an extension of that plugin. If so, let me know and I'll take a look.

**Comment by mmjaeger** [comment]
indeed, I do use this with ACF Pro - hope you'll find a workaround
